---
inputs:
- type: git
  branch: ${GIT_BRANCH}
  service: ${GIT_REPO}
  path: .tekton
triggers:
- type: git
  name: Git Trigger
  service: ${GIT_REPO}
  branch: ${GIT_BRANCH}
  events: {"push":true,"pull_request":false,"pull_request_closed":false}
  eventListener: listener
- type: manual
  name: Manual Trigger
  eventListener: listener
properties:
- name: repository
  value: ${GIT_REPO_URL}
  type: text
- name: revision
  value: ${GIT_BRANCH}
  type: text
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: baseName
  value: ${INPUT_BASENAME}
  type: text
- name: resourceGroup
  value: ${INPUT_RESOURCE_GROUP}
  type: text
- name: region
  value: ${INPUT_REGION}
  type: text
# - name: cluster
#   value: ${PROD_CLUSTER_NAME}
#   type: text 
# - name: registryNamespace
#   value: ${REGISTRY_NAMESPACE}
#   type: text 
# - name: clusterNamespace
#   value: ${PROD_CLUSTER_NAMESPACE}
#   type: text
# - name: clusterRegion
#   value: ${PROD_REGION_ID}
#   type: text
# - name: registryRegion
#   value: ${REGISTRY_REGION_ID}
#   type: text
