version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - code-repo
    - tekton-catalog-repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'simple-tekton-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  code-repo:
    service_id: githubconsolidated
    parameters:
      repo_name: '{{toolchain.name}}'
      source_repo_url: 'https://github.com/l2fprod/simple-tekton-toolchain'
      type: clone
      has_issues: false
      enable_traceability: false
  tekton-catalog-repo:
    service_id: githubconsolidated
    parameters:
      repo_url: "https://github.com/open-toolchain/tekton-catalog"
      source_repo_url: "https://github.com/open-toolchain/tekton-catalog"
      type: "link"
      has_issues: false
      enable_traceability: false
      kind: ['pipeline']
  build:
    service_id: pipeline
    parameters:
      services:
        - code-repo
      name: '{{services.code-repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: code-repo
          GIT_REPO_URL: '{{services.code-repo.parameters.source_repo_url}}'
          GIT_BRANCH: $env.branch
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          INPUT_BASENAME: '{{form.pipeline.parameters.base-name}}'
          INPUT_RESOURCE_GROUP: '{{form.pipeline.parameters.resource-group}}'
          INPUT_REGION: '{{form.pipeline.parameters.region}}'
          INPUT_CLUSTER_NAME: '{{form.pipeline.parameters.cluster-name}}'
          INPUT_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.cluster-namespace}}'
          INPUT_REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          INPUT_SCHEMATICS_WORKSPACE_ID: '{{form.pipeline.parameters.schematics-workspace-id}}'
        #execute: Manual Trigger
form:
  pipeline:
    parameters:
      # allow initialization from environment, i.e from the URL quey parameters
      api-key: '{{apiKey}}'
      base-name: '{{baseName}}'
        # $env.baseName ?
        #   '{{baseName}}' : '{{services.code-repo.parameters.repo_name}}'
      resource-group: '{{resourceGroup}}'
      region: '{{region}}'
      cluster-name: '{{clusterName}}'
      cluster-namespace: >
        $env.clusterNamespace ?
          '{{clusterNamespace}}' : 'default'
      registry-namespace: '{{registryNamespace}}'
      schematics-workspace-id: '{{schematicsWorkspaceId}}'
    schema:
      $ref: deploy.json
