version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  required:
    - build
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'simple-tekton-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  repo:
    service_id: githubconsolidated
    parameters:
      repo_name: '{{toolchain.name}}'
      source_repo_url: 'https://github.com/l2fprod/simple-tekton-toolchain'
      type: clone
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          GIT_REPO_URL: '{{services.repo.parameters.source_repo_url}}'
          GIT_REVISION: main
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          INPUT_BASENAME: '{{form.pipeline.parameters.base-name}}'
          INPUT_RESOURCE_GROUP: '{{form.pipeline.parameters.resource-group}}'
          # REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          # REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          # PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          # PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          # PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: Manual Trigger
form:
  pipeline:
    parameters:
      base-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
