apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
    - name: revision
    - name: apikey
    - name: base-name
    - name: resource-group
    - name: region
    - name: cluster-name
    # - name: registryNamespace
    #   description: the ibmcloud registry namespace
    # - name: registryRegion
    #   description: the ibmcloud registry region
    #   default: us-south
    # - name: cluster
    #   description: The IBM Cloud Kubernetes cluster name
    # - name: clusterRegion
    #   description: The IBM Cloud Kubernetes cluster region
    #   default: us-south
    # - name: clusterNamespace
    #   description: The Kubernetes cluster namespace
    #   default: prod
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(tt.params.repository)
        - name: revision
          value: $(tt.params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: base-name
          value: $(params.base-name)
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: cluster-name
          value: $(params.cluster-name)
        # - name: registryNamespace
        #   value: $(params.registryNamespace)
        # - name: registryRegion
        #   value: $(params.registryRegion)
        # - name: cluster
        #   value: $(params.cluster)
        # - name: clusterRegion
        #   value: $(params.clusterRegion)
        # - name: clusterNamespace
        #   value: $(params.clusterNamespace)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: $(event.repository.html_url)
    - name: revision
      value: $(event.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
