apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
    - name: revision
    - name: apikey
    - name: base-name
    - name: resource-group
    - name: region
    - name: cluster-name
    - name: cluster-namespace
    - name: registry-namespace
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(tt.params.repository)
        - name: revision
          value: $(tt.params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: base-name
          value: $(params.base-name)
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: cluster-namespace
          value: $(params.cluster-namespace)
        - name: registry-namespace
          value: $(params.registry-namespace)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-binding
spec:
  params:
    - name: repository
      value: $(event.repository.html_url)
    - name: revision
      value: $(event.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-listener
spec:
  triggers:
    - binding:
        name: git-binding
      template:
        name: template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-binding
spec:
  params:
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: manual-binding
      template:
        name: template