apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
    - name: revision
    - name: apikey
    - name: base-name
    - name: resource-group
    - name: region
    - name: cluster-name
    # - name: registryNamespace
    #   description: the ibmcloud registry namespace
    # - name: cluster
    #   description: The IBM Cloud Kubernetes cluster name
    # - name: registryRegion
    #   description: the ibmcloud registry region
    #   default: us-south
    # - name: clusterRegion
    #   description: The IBM Cloud Kubernetes cluster region
    #   default: us-south
    # - name: clusterNamespace
    #   description: The Kubernetes cluster namespace
    #   default: prod
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: pipeline-show-env-task
      taskRef:
        name: show-env-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: base-name
          value: $(params.base-name)
        - name: resource-group
          value: $(params.resource-group)
        - name: region
          value: $(params.region)
        - name: cluster-name
          value: $(params.cluster-name)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: build-image
      taskRef:
        name: icr-containerize
      params:
        - name: image-url
          value: us.icr.io/scratch/simple-tekton-toolchain:latest
        - name: resource-group
          value: $(params.resource-group)
        - name: path-to-context
          value: /workspace
      workspaces:
      - name: source
        workspace: pipeline-pvc
    # - name: pipeline-build-task
    #   taskRef:
    #     name: build-task
    #   params:
    #     - name: repository
    #       value: $(params.repository)
    #     - name: revision
    #       value: $(params.revision)
    #     - name: apikey
    #       value: $(params.apikey)
    #     - name: registryNamespace
    #       value: $(params.registryNamespace)
    #     - name: registryRegion
    #       value: $(params.registryRegion)
    #   workspaces:
    #   - name: task-pvc
    #     workspace: pipeline-pvc          
    # - name: pipeline-validate-task
    #   runAfter: [pipeline-build-task]
    #   taskRef:
    #     name: validate-task
    #   params:
    #     - name: repository
    #       value: $(params.repository)
    #     - name: revision
    #       value: $(params.revision)
    #     - name: apikey
    #       value: $(params.apikey)
    #     - name: registryRegion
    #       value: $(params.registryRegion)
    #   workspaces:
    #   - name: task-pvc
    #     workspace: pipeline-pvc            
    # - name: pipeline-deploy-task
    #   runAfter: [pipeline-validate-task]
    #   taskRef:
    #     name: deploy-task
    #   params:
    #     - name: repository
    #       value: $(params.repository)
    #     - name: revision
    #       value: $(params.revision)
    #     - name: apikey
    #       value: $(params.apikey)
    #     - name: cluster
    #       value: $(params.cluster)
    #     - name: clusterRegion
    #       value: $(params.clusterRegion)
    #     - name: clusterNamespace
    #       value: $(params.clusterNamespace)
    #   workspaces:
    #   - name: task-pvc
    #     workspace: pipeline-pvc  
